:LaTeX_PROPERTIES:
#+LANGUAGE: de
#+OPTIONS: d:nil todo:nil pri:nil tags:nil
#+OPTIONS: H:4
#+LaTeX_CLASS: orgstandard
#+LaTeX_CMD: xelatex
:END:

:REVEAL_PROPERTIES:
#+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js
#+REVEAL_REVEAL_JS_VERSION: 4
#+REVEAL_THEME: league
#+REVEAL_EXTRA_CSS: ./mystyle.css
#+REVEAL_HLEVEL: 2
#+OPTIONS: timestamp:nil toc:nil num:nil
:END:

#+TITLE: SSH-Server-Konfiguration
#+SUBTITLE: ITS-Net-Lin
#+AUTHOR: Sebastian Meisel

* Einführung

Der SSH-Server wird in der Datei =/etc/ssh/sshd_config= konfiguriert. Dies ist eine einfache Textdatei. Zeilen, die mit einer Raute (=#=) beginnen, sind auskommentiert, d. h., sie werden nicht eingelesen.

Hier stelle ich eine einfache Konfiguration vor, die einen sicheren SSH-Server einrichtet:

** Weitere Einstellungen in =/etc/ssh/sshd_config.d/= erlauben

Mit dieser Zeile wird ermöglicht, dass zusätzliche Dateien im Unterverzeichnis =/etc/ssh/sshd_config.d/= mit der Endung =.conf= weitere Konfigurationsoptionen enthalten können. So bleibt die Konfiguration übersichtlich:

#+BEGIN_SRC sshd_config :tangle sshd_config
Include /etc/ssh/sshd_config.d/*.conf
#+END_SRC

** Port ändern

SSH lauscht standardmäßig auf Port 22. Dies kann geändert werden, jedoch bringt dies nur geringen Sicherheitsgewinn:

#+BEGIN_SRC sshd_config :tangle sshd_config
Port 2222
#+END_SRC

Wenn diese Einstellung vorgenommen wird, muss zudem die Datei =~/.ssh/config= auf dem Client angepasst werden:

#+BEGIN_SRC 
Host Debian debian deb
    HostName       debian
    Port           2222              # Angepasster Port!
    UserName       <benutzername>
    IdentityFile   ~/.ssh/<key-file>  # Pfad zur Schlüsseldatei
#+END_SRC

=<benutername>= und <key-file> müssen hier natürlich angepasst werden.

* Authentifizierung

Es gibt eine Reihe von Optionen, die bestimmen, wie Benutzer sich auf einem SSH-Server anmelden können. Die Authentifizierung mittels öffentlichem Schlüssel (public key) ist sicher. Daher sollte diese erlaubt und die Anmeldung per Passwort verboten werden:

#+BEGIN_SRC sshd_config :tangle sshd_config
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no
#+END_SRC

Zudem sollte die interaktive Anmeldung per Tastatur deaktiviert werden:

#+BEGIN_SRC sshd_config :tangle sshd_config
KbdInteractiveAuthentication no
#+END_SRC

Auf Linux-Systemen sollte immer der Standard-Anmeldemechanismus ~PAM~ genutzt werden:

#+BEGIN_SRC sshd_config :tangle sshd_config
UsePAM yes
#+END_SRC

** Weitere sinnvolle Einstellungen

Die Spracheinstellungen des Clients sollten durch Umgebungsvariablen an den Server übermittelt werden können:

#+BEGIN_SRC sshd_config :tangle sshd_config
AcceptEnv LANG LC_*
#+END_SRC

Das SFTP-Subsystem sollte aktiviert sein, um Dateiübertragungen wie mit =scp= zu ermöglichen:

#+BEGIN_SRC sshd_config :tangle sshd_config
Subsystem	sftp	/usr/lib/openssh/sftp-server
#+END_SRC

* Hashing und Verschlüsselungsalgorithmen

SSH unterstützt verschiedene Verschlüsselungsalgorithmen. Die folgende Konfiguration erlaubt nur die sichersten Algorithmen:

#+BEGIN_SRC sshd_config :tangle sshd_config
# KEX-(Key Exchange)-Algorithmen zum Schlüsselaustausch
KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
 
# Verschlüsselungsalgorithmen
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
 
# MAC-(message authentication code)-Algorithmen 
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
#+END_SRC

