version: "3.8"
services:
  web:
    image: php:8.2-apache
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: gaestebuch
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  mariadb_data:
